service: images-graphql
frameworkVersion: ">=4.0.0"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2

  environment:
    IMAGES_TABLE: Images
    ARTISTS_TABLE: Artists
    S3_BUCKET_NAME: melbglyphs

  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "Content-Type"
        - "Authorization"
      allowedMethods:
        - OPTIONS
        - POST
      allowCredentials: false

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:BatchWriteItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:ap-southeast-2:412969475996:table/Images
            - arn:aws:dynamodb:ap-southeast-2:412969475996:table/Artists

        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject # optional, if you want to read
            - s3:DeleteObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::melbglyphs/uploads/*

functions:
  graphql:
    handler: graphql-lambda.handler
    layers:
      - arn:aws:lambda:ap-southeast-2:412969475996:layer:heic-sharpv2:2

    events:
      - httpApi:
          path: /graphql
          method: POST
      - httpApi:
          path: /graphql
          method: OPTIONS
